---
version: "3"

services:
  vault:
    image: vault:0.9.5
    cap_add:
    - IPC_LOCK
    environment:
    - VAULT_DEV_ROOT_TOKEN_ID
    - VAULT_DEV_LISTEN_ADDRESS
    ports:
    - "8200:8200"
    command: server -dev -log-level=debug
